#1
SELECT O.SERIALNO, O.REGNO, M.MANNAME FROM CAR_OWNERSHIP O, CAR C, MANUFACT M WHERE  C.SERIALNO = O.SERIALNO AND C.MANID = M.MANID AND SSNID IN (SELECT SSNID FROM person WHERE pername ='Mrs. Xena') AND OWNERSHIPSTATUS = 'Ownedbyperson'; 

#2
(SELECT MANID, MANNAME FROM MANUFACT) MINUS (SELECT MANID,MANNAME FROM MANUFACT NATURAL JOIN CAR);

#3

SELECT PERNAME, COUNT(1) AS CARSOWNED FROM (SELECT DISTINCT PERNAME, SERIALNO FROM CAR_OWNERSHIP, PERSON  WHERE PERSON.SSNID=CAR_OWNERSHIP.SSNID UNION SELECT DISTINCT PERNAME, SERIALNO FROM CAR_TRASFERING, PERSON WHERE CAR_TRASFERING.SSNIDTO = PERSON.SSNID) VW GROUP BY PERNAME HAVING COUNT(1) = 1 ;  

#4
SELECT PERNAME, COUNT(1) AS CARSOWNED FROM (SELECT DISTINCT PERNAME, SERIALNO FROM CAR_OWNERSHIP, PERSON  WHERE PERSON.SSNID=CAR_OWNERSHIP.SSNID UNION SELECT DISTINCT PERNAME, SERIALNO FROM CAR_TRASFERING, PERSON WHERE CAR_TRASFERING.SSNIDTO = PERSON.SSNID) VW GROUP BY PERNAME HAVING COUNT(1) > 1 ; 


#5
SELECT DISTINCT  M.MDLNAME FROM CAR_OWNERSHIP O, CAR C , MODEL M WHERE O.SERIALNO= C.SERIALNO AND DLRID ='2' AND C.MDLID= M.MDLID;

#6
SELECT DISTINCT DLRNAME FROM (SELECT  DLRNAME FROM DELIVERY,CAR, DEALER WHERE DEALER.DLRID=DELIVERY.DLRID AND DELIVERY.SERIALNO = CAR.SERIALNO AND CAR.MDLID IN (SELECT MDLID FROM CAR WHERE SERIALNO IN (SELECT SERIALNO FROM DELIVERY WHERE DLRID = (SELECT DLRID FROM  DEALER WHERE DLRNAME ='Jones Brothers Ltd')) OR SERIALNO IN  (SELECT SERIALNO FROM CAR_OWNERSHIP WHERE DLRID = (SELECT DLRID FROM  DEALER WHERE DLRNAME ='Jones Brothers Ltd')) ) UNION SELECT  DLRNAME FROM CAR_OWNERSHIP ,CAR, DEALER WHERE DEALER.DLRID=CAR_OWNERSHIP.DLRID AND CAR_OWNERSHIP.SERIALNO = CAR.SERIALNO AND CAR.MDLID IN (SELECT MDLID FROM CAR WHERE SERIALNO IN (SELECT SERIALNO FROM DELIVERY WHERE DLRID = (SELECT DLRID FROM  DEALER WHERE DLRNAME ='Jones Brothers Ltd')) OR SERIALNO IN  (SELECT SERIALNO FROM CAR_OWNERSHIP WHERE DLRID = (SELECT DLRID FROM  DEALER WHERE DLRNAME ='Jones Brothers Ltd')) )) VW WHERE DLRNAME != 'Jones Brothers Ltd';

#7
SELECT * FROM (SELECT C.SERIALNO, M.MANNAME, MDL.MDLNAME, EXTRACT(YEAR FROM C.PYEAR) - EXTRACT(YEAR FROM D.DDATE) AS SHORTESTLIFESPAN FROM CAR C, DESTRUCTION D, MANUFACT M, MODEL MDL WHERE C.MANID=M.MANID AND C.MDLID = MDL.MDLID AND C.SERIALNO = D.SERIALNO  ORDER BY SHORTESTLIFESPAN DESC) WHERE  rownum <= 1;

#8.    
SELECT M.MANNAME, MDL.MDLNAME, - ROUND(AVG(EXTRACT(YEAR FROM C.PYEAR) - EXTRACT(YEAR FROM D.DDATE))) AS AVGLIFESPAN FROM CAR C, DESTRUCTION D, MANUFACT M, MODEL MDL WHERE C.MANID=M.MANID AND C.MDLID = MDL.MDLID AND C.SERIALNO = D.SERIALNO  GROUP BY M.MANNAME, MDL.MDLNAME ORDER BY AVGLIFESPAN DESC;


#9.
SELECT * FROM (SELECT M.MANNAME, MDL.MDLNAME, - ROUND(AVG(EXTRACT(YEAR FROM C.PYEAR) - EXTRACT(YEAR FROM D.DDATE))) AS LONGLIFESPAN FROM CAR C, DESTRUCTION D, MANUFACT M, MODEL MDL WHERE C.MANID=M.MANID AND C.MDLID = MDL.MDLID AND C.SERIALNO = D.SERIALNO  GROUP BY M.MANNAME, MDL.MDLNAME ORDER BY LONGLIFESPAN DESC) WHERE  rownum <= 1;

#10
SELECT DISTINCT SERIALNO, REGNO, TO_CHAR(RDATE, 'YYYY-MM-DD') AS RDATE, SELLER, NEWOWNER FROM(SELECT SERIALNO, REGNO, RDATE, A.PERNAME AS SELLER, B.PERNAME AS NEWOWNER FROM CAR_TRASFERING, PERSON A, PERSON B WHERE A.SSNID= SSNIDFROM AND B.SSNID = SSNIDTO UNION SELECT SERIALNO, REGNO, RDATE, CASE WHEN OWNERSHIPSTATUS = 'Ownedbydealer' THEN (SELECT PERNAME FROM PERSON WHERE PERSON.SSNID = CAR_OWNERSHIP.SSNID) ELSE (SELECT DLRNAME FROM DEALER WHERE DEALER.DLRID = CAR_OWNERSHIP.DLRID) END AS SELLER, CASE WHEN OWNERSHIPSTATUS = 'Ownedbyperson' THEN (SELECT PERNAME FROM PERSON WHERE PERSON.SSNID = CAR_OWNERSHIP.SSNID) ELSE (SELECT DLRNAME FROM DEALER WHERE DEALER.DLRID = CAR_OWNERSHIP.DLRID) END AS NEWOWNER FROM CAR_OWNERSHIP) VW ORDER BY RDATE ASC;